# Generated by Django 3.2.5 on 2022-01-19 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0002_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesperson',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='region', to='rate.region'),
        ),
    ]
